name: Build-Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push:
    name: ${{ matrix.os }} - (Docker image build)
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: Build Docker image
        shell: bash
        run: |
          chmod +x ./build_container.sh
          ./build_container.sh ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Deploy
        run: docker image push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/minimal-docker-image

